source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DialogView_Example' do
  pod 'DialogView', :path => '../'
  pod 'SnapKit', '~> 3.0'
end

target 'DialogView_Tests' do
  pod 'DialogView', :path => '../'

  pod 'SnapKit', '~> 3.0'
end
