source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DialogView_Example', :exclusive => true do
  pod 'DialogView', :path => '../'
  pod 'SnapKit', '~> 0.19.1'
end

target 'DialogView_Tests', :exclusive => true do
  pod 'DialogView', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  pod 'SnapKit', '~> 0.19.1'
end
